version: '3.8'

services:
  student-performance-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    volumes:
      - ./artifact:/app/artifact
    restart: unless-stopped
